### ISSUE TITLE
Retain last query in popout window after it closes

### ISSUE THREAD

**Issue by SpitFire-666** [fastaddons/AI-Anywhere#8]
**Is your feature request related to a problem? Please describe.**
If you click anywhere outside of the AI popup, it closes, losing your query and result. 

**Describe the solution you'd like**
Either let the popup window stay open til user closes it, or retain the last query and answer when re-opening the popup.

**Describe alternatives you've considered**
I want to avoid having to open a tab/window (to me defeats the purpose of the addon)

**Additional context**
Thanks!

**Comment by Juraj-Masiar** [comment]
Hello,
Sadly, addons cannot control the popup open state - browser will close it automatically once it looses the focus.
Note that ChatGPT saves all conversations so if it generated response, you will see it in your history in the left side.
Alternatively, change the "Context menu action" or "Toolbar icon action" in the addon settings to open not in Popup but in a "New window". That way it won't close and you can even move and resize it. And since it's a special "popup type" window, your browser will not use it for new tabs.

And one more tip - you can re-enter previous query by pressing arrow UP.

I know these are not perfect workarounds but the addon possibilities are very limited :(

**Comment by SpitFire-666** [comment]
Thanks for the explanation, understood. I'll live with it!

Maybe a sidebar could be the way to go? Anyways you can close this ticket, cheers

**Comment by Juraj-Masiar** [comment]
I can do the sidebar for sure! I've done it in my some of my other addons so here it should be piece of cake :)
I'll try to add it later this week (maybe on weekend since I have a lot of things I want to finish).

**Comment by garyyeap** [comment]
Is it implemented? Where can I switch to the sidebar-based mode?

**Comment by garyyeap** [comment]
> I can do the sidebar for sure! I've done it in my some of my other addons so here it should be piece of cake :) I'll try to add it later this week (maybe on weekend since I have a lot of things I want to finish).

Is it implemented? Where can I switch to the sidebar-based mode?

**Comment by garyyeap** [comment]
@Juraj-Masiar Could you reopen this issue? Since there is no sidebar option.

**Comment by Juraj-Masiar** [comment]
@garyyeap I've created new issue for sidebar here:
https://github.com/fastaddons/AI-Anywhere/issues/29

I'll try to implement it in the upcoming release, but I'm not sure when will that be, there is a lot of work to be done of my other extensions too...
